# fly.toml app configuration file generated for raulm2x-part3 on 2023-12-22T11:15:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "raulm2x-part3"
primary_region = "bog"

[env]
  PORT = "3000" # add this

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
